name: Workflow1

on:
  workflow_dispatch:
    inputs: 
      workflow2_name:
        description: 'Workflow2 Name for Triggering'
        required: true
        default: 'Workflow2'
      
      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'Balajii-Codoid'
      
      workflow2_repo_github:
        description: 'GitHub Repository Name'
        required: true
        default: 'DemoGitActions'

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      pat_token: ${{ secrets.G_ACCESS_TOKEN }}
      payload_Baseline_Number: "BSL_001"
      payload_Baseline_Revision: "zsfdgsdbgngffdwdx1dxvv2"

    steps:
      - uses: actions/checkout@v3

      - name: Display Workflow Inputs
        run: |
          echo "PAT Token: ${{ secrets.G_ACCESS_TOKEN }}"
          echo "Workflow2 Name: ${{ github.event.inputs.workflow2_name }}"
          echo "GitHub Account Owner: ${{ github.event.inputs.workflow2_github_account }}"
          echo "GitHub Repository Name: ${{ github.event.inputs.workflow2_repo_github }}"
          echo "Payload Baseline Number: ${{ env.payload_Baseline_Number }}"
          echo "Payload Baseline Revision: ${{ env.payload_Baseline_Revision }}"

      - name: Trigger Workflow2
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.G_ACCESS_TOKEN }}" \
            https://api.github.com/repos/${{ github.event.inputs.workflow2_github_account }}/{{ github.event.inputs.workflow2_repo_github }}/dispatches \
            -d '{"event_type":"Workflow1","client_payload":{"baselinetag":"${{ env.payload_Baseline_Number }}","revision_number":"${{ env.payload_Baseline_Revision }}"}}'
