# This is a basic workflow to help you get started with Actions

name: Workflow1

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs: 
      workflow2_name:
        description: 'Workflow2 Name for Triggering'
        required: true
        default: 'maven'
      
      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'Balajii-Codoid'
      
      workflow2_repo_github:
        description: 'GitHub Repository Name'
        required: true
        default: 'DemoGitActions'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      pat_token: ${{ secrets.G_ACCESS_TOKEN }}
      payload_Baseline_Number: "BSL_001"
      payload_Baseline_Revision: "zsfdgsdbgngffdwdx1dxvv2"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Display Workflow Inputs
        run: |
          echo "PAT Token: ${{ secrets.G_ACCESS_TOKEN }}"
          echo "Workflow2 Name: ${{ github.event.inputs.workflow2_name }}"
          echo "GitHub Account Owner: ${{ github.event.inputs.workflow2_github_account }}"
          echo "GitHub Repository Name: ${{ github.event.inputs.workflow2_repo_github }}"
          echo "Payload Baseline Number: ${{ env.payload_Baseline_Number }}"
          echo "Payload Baseline Revision: ${{ env.payload_Baseline_Revision }}"
